version: 2.0

jobs:
  build:
    working_directory: ~/kotlin-extensions

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run:
          name: Compile
          command: ./gradlew assemble
      - store_artifacts:
          path: build/outputs/aar

      - run:
          name: JVM Tests & Lint
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/test-results
      - store_artifacts:
          path: build/reports/lint-results.html

      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - store_test_results:
          path: build/reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
